sudo: required

services:
  - docker

env:
  matrix :
    - env:
      VERSION: '8.7.0'
    - env:
      VERSION: '6.11.5'
    - env:
      VERSION: '4.8.4'

install:
  - docker build -t "lgatica/node-krb5:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-krb5:$VERSION" node --version

notifications:
  email: false
